# COLORS
# Battery
PROGRESSCOLOR = "#8A9A5B"
BACKPROGRESSCOLOR = '#71797E'
YELLOWBATTERY = '#FAdA5F'
REDBATTERY = '#A01641'

ORANGE = '#e69138'
DONWLOADOFF = '#6CCBD1'
PANELCOLOR = '#333333' # The color of the panel
SLIDER_BG = '#64686B' #The color back of the sliders and the graph color
GRAPHFACECOLOR = '#303030'
WHITE = '#E1E1E1' # The white parts

GRAPHBACKCOLOR = '#191970' # The color of the external part of the graph # Blue
RED = '#8a0606'
#RED = '	#701919'
YELLOW = '#e5af0d'
PINK = '#C54B8C'
DARKGRAY ='#2c2c2c'

# VALUES
MAX_OUTPUT = 60
MIN_OUTPUT = -60
DEFAULT_SPEED = 50
DEFAULT_HEIGHT = 50
DEFAULT_PROPORTIONAL_VALUE_HEIGHT = 1.6
DEFAULT_INTEGRAL_VALUE_HEIGHT = 0.6 #0.6
DEFAULT_DERIVATIVE_VALUE_HEIGHT = 0.4 #0.4
PROGRESSDEFAULT = 0.78 #Battery
ALTITUDE = 5
DEFAULT_SPEED = 50

MIN_SLIDER_VALUE_HEIGHT = 10
MAX_SLIDER_VALUE_HEIGHT = 500
MIN_SLIDER_VALUE_PROPORTIONAL = 0
MAX_SLIDER_VALUE_PROPORTIONAL = 2
MIN_SLIDER_VALUE_INTEGRAL = 0
MAX_SLIDER_VALUE_INTEGRAL = 2
MIN_SLIDER_VALUE_DERIVATIVE = 0
MAX_SLIDER_VALUE_DERIVATIVE = 2
MIN_SLIDER_VALUE_SPEED = 0
MAX_SLIDER_VALUE_SPEED = 100

OPTIONS_DRONE_GRAPH1 = ['Height', 'SP', 'None', 'Both']
OPTIONS_DRONE_GRAPH2 = ['Error', 'Signal', 'None', 'Both']
OPTIONS_DRONE_GRAPH_STATE = ['Incremental', 'Real Time']
